name: Compile

on:
 workflow_dispatch:
 push:
   branches:
     - "master"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2


    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
    
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}

    - name: Move discord dll
      working-directory: ${{env.SOLUTION_FILE_PATH}}\x64\Release\
      run: Rename-Item ${{env.SOLUTION_FILE_PATH}}\discord_game_sdk.dll discord_game_sdk.dll

    - name: Upload the files
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        working-directory: ${{env.SOLUTION_FILE_PATH}}\x64\Release
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "build"
        title: "Builds"
        files:  | 
          discord_game_sdk.dll
          TeardownRPC.exe
